import Canvas from "@/components/Canvas";
import Head from "next/head";
import React from "react";
// import { Inter } from "next/font/google";

export default function Home() {
  const [mediaText, setMediaText] = React.useState("MEDIAGENZ");
  const [caption, setCaption] = React.useState(
    "Caption Berita Yang Gak Penting Penting Amat. Tapi Gen Z Tetap Aja Percaya. Padahal Mah Dibodo bodoin. Modal Backround Putih Caption Text Hitam"
  );
  const [mediaPosition, setMediaPosition] = React.useState("tr");
  const [captionControl, setCaptionControl] = React.useState({
    align: "center",
    topOffset: 0,
    maxWidth: 480,
  });

  return (
    <>
      <Head>
        <title>Postingan Media Gen Z</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="h-full max-w-lg mx-auto py-4 px-4 shadow-lg flex flex-col space-y-2">
        <div>
          <label
            htmlFor="media"
            className="block text-sm font-medium leading-6 text-gray-900"
          >
            Media
          </label>
          <div className="mt-2">
            <input
              id="media"
              name="media"
              className="w-full px-2 py-2 rounded-md border-gray-400 border"
              placeholder="ICKWR"
              defaultValue={""}
              onChange={(e) => setMediaText(e.target.value)}
            />
          </div>
        </div>
        <div>
          <label
            htmlFor="mediaPosition"
            className="block text-sm font-medium leading-6 text-gray-900"
          >
            Media Position
          </label>
          <select
            id="mediaPosition"
            className="w-full px-2 py-2 rounded-md border-gray-400 border"
            value={mediaPosition}
            onChange={(e) => {
              setMediaPosition(e.target.value);
            }}
          >
            <option selected>Pilih posisi</option>
            <option value="tl">Atas Kiri</option>
            <option value="tr">Atas Kanan</option>
            <option value="bl">Bawah Kiri</option>
            <option value="br">Bawah Kanan</option>
          </select>
        </div>
        <div>
          <label
            htmlFor="caption"
            className="block text-sm font-medium leading-6 text-gray-900"
          >
            Caption
          </label>
          <div className="mt-2">
            <textarea
              id="caption"
              name="caption"
              rows={4}
              className="w-full px-2 py-2 rounded-md border-gray-400 border"
              placeholder="kulkas LG 2 pintu minat inbok"
              defaultValue={""}
              onChange={(e) => setCaption(e.target.value)}
            />
          </div>
        </div>
        <div className="flex space-x-2">
          <div className="w-44">
            <label
              htmlFor="align"
              className="block text-sm font-medium leading-6 text-gray-900"
            >
              Caption Align
            </label>
            <div className="mt-2">
              <select
                id="mediaPosition"
                className="w-full px-2 py-2 rounded-md border-gray-400 border"
                value={captionControl.align}
                onChange={(e) => {
                  setCaptionControl({
                    ...captionControl,
                    align: e.target.value,
                  });
                }}
              >
                <option selected>Pilih align</option>
                <option value="left">Left</option>
                <option value="right">Right</option>
                <option value="center">Center</option>
              </select>
            </div>
          </div>
          <div className="">
            <label
              htmlFor="topOffset"
              className="block text-sm font-medium leading-6 text-gray-900"
            >
              Top Offset
            </label>
            <div className="mt-2">
              <input
                id="topOffset"
                name="topOffset"
                className="w-full px-2 py-2 rounded-md border-gray-400 border"
                placeholder="0"
                defaultValue={""}
                value={captionControl.topOffset}
                onChange={(e) =>
                  setCaptionControl({
                    ...captionControl,
                    topOffset: parseInt(e.target.value),
                  })
                }
                type="number"
              />
            </div>
          </div>
          <div className="">
            <label
              htmlFor="maxWidth"
              className="block text-sm font-medium leading-6 text-gray-900"
            >
              Max Width
            </label>
            <div className="mt-2">
              <input
                id="maxWidth"
                name="maxWidth"
                className="w-full px-2 py-2 rounded-md border-gray-400 border"
                placeholder="480"
                defaultValue={"480"}
                onChange={(e) =>
                  setCaptionControl({
                    ...captionControl,
                    maxWidth: parseInt(e.target.value),
                  })
                }
                type="number"
              />
            </div>
          </div>
        </div>
        <div className="">
          <Canvas
            mediaText={mediaText}
            caption={caption}
            mediaPosition={mediaPosition}
            captionControl={captionControl}
          />
        </div>
      </div>
    </>
  );
}
